gecko_driver_path = '/Users/administrator/Desktop/Projects/djangoProjects/web_trial/backend/frontend/Driver/geckodriver'
url = ' http://127.0.0.1:8000/'
property_xpath = '/html/body/header/div/div/div/nav/ul/li[2]/a' 
details_xpath = '/html/body/header/div/div/div/nav/ul/li[3]/a'
contact_xpath = '/html/body/header/div/div/div/nav/ul/li[4]/a'
home_xpath = '/html/body/header/div/div/div/nav/ul/li[1]/a'
property_url = 'http://127.0.0.1:8000/properties.html'